$wallpaper = /home/xdx/Pictures/Wallpapers/wallhaven-1q23yg.jpg
$background = 11150d
$foreground = e0e4d7

$primary = 97da6c
$secondary = b2cf9b
$tertiary = 43dfc4
$surface = 11150d
$surface_bright = 363b32
$outline = 8b9382
$error = 000000

$shadow = 000000
